spring:
  data:
    mongodb:
     uri: ${MONGO_URI:mongodb://mongocontainer:27017/auth_db}
  cloud:
    loadBalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
    
zuul:
  ignoredServices: '*'
  routes:
    patient-service:
      path: /api/patients/**
      serviceId: patient-service
    contact-service:
      path: /api/contacts/**
      serviceId: contact-service
  host:
    connect-timeout-millis: 60000
  

logging.level.org.springframework.web: DEBUG
