spring:
  profiles:
    - docker
  data:
    mongodb:
     uri: mongodb://mongocontainer:27017/auth_db

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    eureka-server-read-timeout-seconds: 30
    
zuul:
  prefix: /api
  routes:
    patient-service:
      path: /patients/**
      url: http://localhost:8081/
      stripPrefix: false
    contact-service:
      path: /contacts/**
      url: http://localhost:8084/
      stripPrefix: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
            
ribbon:
  readTimeout: 10000