spring:
  profiles:
    - docker
  data:
    mongodb:
     uri: mongodb://mongocontainer:27017/auth_db

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    registerWithEureka: false
    fetchRegistry: true
    
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    patient-service:
      path: /patients/**
      serviceId: patient-service
      stripPrefix: true
    contact-service:
      path: /contacts/**
      serviceId: contact-service
      stripPrefix: true
