spring:
  profiles:
    - docker
  data:
    mongodb:
     uri: ${MONGO_URI:mongodb://mongocontainer:27017/auth_db}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
    
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    patient-service:
      path: /patients/**
      serviceId: patient-service
      stripPrefix: false
    contact-service:
      path: /contacts/**
      serviceId: contact-service
      stripPrefix: false
  host:
    connect-timeout-millis: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

logging.level.org.springframework.web: DEBUG
