spring:
  profiles:
    - docker
  data:
    mongodb:
     uri: mongodb://mongocontainer:27017/auth_db

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    eureka-server-read-timeout-seconds: 30
    
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    patient-service:
      path: /patients/**
      serviceId: patient-service
      stripPrefix: false
    contact-service:
      path: /contacts/**
      serviceId: contact-service
      stripPrefix: false


ribbon:
  eureka:
    enabled: false