spring:
  profiles:
    - docker
  data:
    mongodb:
     uri: mongodb://mongocontainer:27017/auth_db

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    patient-service:
      path: /patients/**
      serviceId: http://patient-service:8081/
      stripPrefix: true
    contact-service:
      path: /contacts/**
      url: http://contact-service:8084/
      stripPrefix: true


logging.level.org.springframework.web: DEBUG