spring:
  profiles:
    - docker
  data:
    mongodb:
     uri: ${MONGO_URI:mongodb://localhost:27017/auth_db}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http:localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
    
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    patient-service:
      path: /patients/**
      serviceId: patient-service
      stripPrefix: false
    contact-service:
      path: /contacts/**
      serviceId: contact-service
      stripPrefix: false

logging.level.org.springframework.web: DEBUG