spring:
  profiles:
    - docker
  data:
    mongodb:
     uri: mongodb://mongocontainer:27017/auth_db

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    
zuul:
  retryable: true
  ignoredServices: '*'
  prefix: /api
  routes:
    patient-service:
      path: /patients/**
      serviceIs: patient-service
    contact-service:
      path: /contacts/**
      serviceId: contact-service

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
  
logging.level.org.springframework.web: DEBUG