spring:
  profiles:
    - docker
  data:
    mongodb:
     uri: mongodb://mongocontainer:27017/contact_db
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        contact_input:
          destination: contact-exchange
          group: contact-queue