spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
     uri: mongodb://localhost:27017/contact_db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        contact_input:
          destination: contact-exchange
          group: contact-queue
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
    eureka-server-read-timeout-seconds: 30
