spring:
  data:
    mongodb:
      host: localhost
      database: contact_db
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        contact_input:
          destination: contact-exchange
          group: contact-queue