spring:
  profiles:
  - docker
  data:
    mongodb:
     uri: ${MONGO_URI:mongodb://mongocontainer:27017/contact_db}
  rabbitmq:
    host: ${RABBITMQ_URI:localhost}
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        contact_input:
          destination: contact-exchange
          group: contact-queue
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
    eureka-server-read-timeout-seconds: 30
