spring:
  profiles:
    - docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
spring:
  data:
    mongodb:
     uri: mongodb://mongocontainer:27017/patient_db
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        patient_output:
          destination: patient-exchange
        contact_output:
          destination: contact-exchange
    loadbalancer:
      ribbon:
        enabled: false
  
