spring:
  profiles:
    - docker
  data:
    mongodb:
     uri: mongodb://mongocontainer:27017/patient_db
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        patient_output:
          destination: patient-exchange
        contact_output:
          destination: contact-exchange
        address_input:
          destination: address-exchange
          group: address-queue
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    eureka-server-read-timeout-seconds: 30
