spring:
  data:
    mongodb:
      host: localhost
      database: patient_db
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        patient_output:
          destination: patient-exchange
        contact_output:
          destination: contact-exchange
  