spring:
  profiles:
    - docker
  data:
    mongodb:
     uri: ${MONGO_URI:mongodb://mongocontainer:27017/queueing_db}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        patient_input:
          destination: patient-exchange
          group: patient-queue
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
    eureka-server-read-timeout-seconds: 30
