spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
     uri: mongodb://localhost:27017/user_db
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
    eureka-server-read-timeout-seconds: 30
