eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://discovery-server:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
spring:
  data:
    mongodb:
      host: localhost
      database: ward_db
      port: 27017
